imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# MongoDB ODM Configuration
doctrine_mongodb:
    connections:
        default:
            server: %mongodb_server%
            options: {}
    default_database: %mongodb_name%
    document_managers:
        default:
            auto_mapping: true