imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

# Wix API Configuration
wix_api:
    classes:
        service: Wix\APIBundle\Base\Bridge
        instance: Wix\APIBundle\Base\Instance

    keys:
        app_id: %wix_app_id%
        app_secret: %wix_app_secret%

# Google OAuth2 Configuration
google_apio_auth2:
    keys:
        client_id: 945840538324.apps.googleusercontent.com
        client_secret: hD3pGqJf-xa5FxIfBm_5nhGd
        refresh_token: 1/9QrmGVvG6zOu9Jna1UDBHon-1Mww_pL9NEzRJl_aY0k

    urls:
        redirect_uri: https://www.adsense.apps.wix.com/settings/redirect

    scopes:
        [ https://www.googleapis.com/auth/adsensehost ]

    preferences:
        use_objects: true

ekino_new_relic:
    application_name: Google AdSense
    api_key: "%ekino_new_relic_api_key%"
    log_exceptions: true

# MongoDB ODM Configuration
doctrine_mongodb:
    connections:
        default:
            server: %mongodb_server%
            options:
              replicaSet: ~
              connect: true
    default_database: %mongodb_name%
    document_managers:
        default:
            auto_mapping: true