imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ WixGoogleAdSenseAppBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# MongoDB ODM Configuration
doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: wix_adsense
    document_managers:
        default:
            auto_mapping: true

# Wix API Configuration
wix_api:
    classes:
        service: Wix\APIBundle\Base\Bridge
        instance: Wix\APIBundle\Base\Instance

    keys:
        app_id: 12d5833e-f061-7cc8-5122-e1d404f6c8ae
        app_secret: d8f2bb9f-7ea1-4a15-b2af-acca6be60fe8

# Google OAuth2 Configuration
google_apio_auth2:
    keys:
        client_id: 945840538324.apps.googleusercontent.com
        client_secret: hD3pGqJf-xa5FxIfBm_5nhGd
        redirect_uri: http://local.adsense.apps.wix.com/app_dev.php/settings/redirect

    scopes:
        [ https://www.googleapis.com/auth/adsensehost ]

    preferences:
        use_objects: true

# Wix Google AdSense Configuration
wix_google_ad_sense_app:
    refresh_token: 1/9QrmGVvG6zOu9Jna1UDBHon-1Mww_pL9NEzRJl_aY0k