imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

# Wix API Configuration
wix_api:
    classes:
        service: Wix\APIBundle\Base\Bridge
        instance: Wix\APIBundle\Base\Instance

    keys:
        app_id: 1330f382-7b44-f3bb-86e8-48b76f901d91
        app_secret: 2ba44c22-672b-41b2-858c-7eb1604b190f
#        app_id: 12d5833e-f061-7cc8-5122-e1d404f6c8ae
#        app_secret: d8f2bb9f-7ea1-4a15-b2af-acca6be60fe8

# Google OAuth2 Configuration
google_apio_auth2:
    keys:
        client_id: 417424657964.apps.googleusercontent.com
        client_secret: R1R9PiJd4j9kVT-X4xQf1y76
        redirect_uri: http://local.adsense.apps.wix.com/app_dev.php/settings/redirect

    scopes:
        [ https://www.googleapis.com/auth/adsensehost ]

    preferences:
        use_objects: true

# Wix Google AdSense Configuration
wix_google_adsense:
    refresh_token: 1/-tOgUd17_soJ1an9Z99Nv9vbfeCBvhAQNPeMkKA7oUo
