imports:
    - { resource: config.yml }


monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

# Wix API Configuration
wix_api:
    classes:
        service: Wix\APIBundle\Base\Bridge
        instance: Wix\APIBundle\Base\Instance

    keys:
        app_id: 133190a9-0b50-0090-e6d2-44c93b6e2bde
        app_secret: 0cc4bb17-fc85-4af8-b411-0c00923187d3

# Google OAuth2 Configuration
google_apio_auth2:
    keys:
        client_id: 417424657964.apps.googleusercontent.com
        client_secret: R1R9PiJd4j9kVT-X4xQf1y76
        redirect_uri: http://http://adsense.wix.codeoasis.com/settings/redirect

    scopes:
        [ https://www.googleapis.com/auth/adsensehost ]

    preferences:
        use_objects: true

# Wix Google AdSense Configuration
wix_google_ad_sense_app:
    refresh_token: 1/-tOgUd17_soJ1an9Z99Nv9vbfeCBvhAQNPeMkKA7oUo
