imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

# MongoDB ODM Configuration
doctrine_mongodb:
    connections:
        default:
            server: %mongodb_server%
            options: {}
    default_database: %mongodb_name%
    document_managers:
        default:
            auto_mapping: true

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

# Wix API Configuration
wix_api:
    classes:
        service: Wix\APIBundle\Base\Bridge
        instance: Wix\APIBundle\Base\Instance

    keys:
        app_id: %wix_app_id%
        app_secret: %wix_app_secret%

# Google OAuth2 Configuration
google_apio_auth2:
    keys:
        client_id: 417424657964.apps.googleusercontent.com
        client_secret: R1R9PiJd4j9kVT-X4xQf1y76
        refresh_token: 1/-tOgUd17_soJ1an9Z99Nv9vbfeCBvhAQNPeMkKA7oUo

    urls:
        redirect_uri: http://local.adsense.apps.wix.com/app_dev.php/settings/redirect

    scopes:
        [ https://www.googleapis.com/auth/adsensehost ]

    preferences:
        use_objects: true

# Wix Google AdSense Configuration
#wix_google_adsense:
#    refresh_token: 1/-tOgUd17_soJ1an9Z99Nv9vbfeCBvhAQNPeMkKA7oUo
